version: "3.7"

services:
    backendactiviza:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./backendactiviza:/backendactiviza
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment:
            - DEBUG=1
            - ALLOWED_HOSTS=127.0.0.1,localhost,34.125.175.117,10.182.0.2
