version: "3.7"

services:
    backend:
        build:
            context: .
        volumes:
            - static_data:/vol/web
            - ./backend:/backend
        environment:
            - SECRET_KEY=gajKHFGAHgafhas77a6s8o7agHJAGFIUASGghkf
        depends_on:
            - db

    db:
        image: postgres:16.3-alpine3.19
        environment:
            POSTGRES_PASSWORD: postgres_gjkhagsdGAJGDiasyf78asfgiasy7fiagjHGAHFGA

    proxy: 
        build:
            context: ./proxy
        volumes:
          - static_data:/vol/static
        ports:
          - "8080:8080"
        depends_on:
            - backend

volumes:
    static_data:
