version: '3.7'

services:
    dashpack:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./dashpack:/dashpack
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1
            - ALLOWED_HOSTS=127.0.0.1,localhost