version: '3.7'

services:
    db:
        image: "postgres:alpine"
        env_file:
            - web.env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
  
    dashpack:
        build:
            context: .
        volumes:
            - static_data:/vol/web
        env_file:
            - web.env
        environment:
            - ALLOWED_HOSTS=127.0.0.1,localhost
        depends_on:
            - db
    proxy:
        build:
            context: ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "8080:8080"
        depends_on:
            - dashpack

volumes:
    static_data:
    postgres_data:
