version: "3.7"

services:
    backend:
        build:
            context: .
        ports:
            - "80:80"
        volumes:
            - ./backend:/backend
        command: sh -c "python manage.py migrate" && sh -c "python manage.py runserver 0.0.0.0:80"
        environment:
            - DEBUG=1
            - ALLOWED_HOSTS=127.0.0.1,localhost,34.125.175.117,10.182.0.2
