# Generated by Django 5.0.4 on 2024-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('repeticiones', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('descanso', models.IntegerField()),
                ('media', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=1000)),
                ('descripcion', models.CharField(max_length=1000)),
                ('ejercicios', models.ManyToManyField(to='activiza.ejercicio')),
            ],
        ),
    ]
