# Generated by Django 5.0.4 on 2024-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='media',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
