# Generated by Django 5.0.4 on 2024-04-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0003_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='entrenador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activiza.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
