# Generated by Django 5.0.4 on 2024-04-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0004_rutina_entrenador_alter_rutina_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='repeticiones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
