# Generated by Django 5.0.4 on 2024-04-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0005_alter_ejercicio_duracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activiza.usuario'),
        ),
    ]
