# Generated by Django 5.0.4 on 2024-04-14 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0007_alter_rutina_entrenador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alumnos',
            field=models.ManyToManyField(blank=True, null=True, to='activiza.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='objetivo',
            field=models.CharField(default='perder_peso', max_length=1000),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=1000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
