# Generated by Django 5.0.4 on 2024-04-15 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0009_alter_usuario_alumnos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicaciones',
            new_name='Publicacion',
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altura', models.FloatField(max_length=5)),
                ('peso', models.FloatField(max_length=5)),
                ('objetivo', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activiza.entrenador')),
            ],
        ),
        migrations.AlterField(
            model_name='rutina',
            name='entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activiza.entrenador'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
