# Generated by Django 5.0.4 on 2024-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0010_rename_publicaciones_publicacion_entrenador_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='media',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
