# Generated by Django 5.0.4 on 2024-05-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0013_remove_rutina_tipo_rutina_genero_rutina_lugar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutina',
            old_name='lugar',
            new_name='lugar_entrenamiento',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lugar_entrenamiento',
            field=models.CharField(choices=[('C', 'Casa'), ('G', 'Gimnasio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='objetivo',
            field=models.CharField(choices=[('GRASA', 'Perder grasa'), ('MUSCULO', 'Ganar musculo')], max_length=7),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='objetivo',
            field=models.CharField(choices=[('GRASA', 'Perder grasa'), ('MUSCULO', 'Ganar musculo')], max_length=7),
        ),
    ]
