# Generated by Django 5.0.4 on 2024-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0014_rename_lugar_rutina_lugar_entrenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='media',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
