# Generated by Django 5.0.4 on 2024-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activiza', '0015_publicacion_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
